config/routes.rb
Rails.application.routes.draw do
  post 'support/request_support'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :subscriptions, only: [:create, :show]

  get 'onboarding-passed', to: 'onboardings#set_passed', as: 'onboarding_passed'
  get 'alert-passed', to: 'alerts#set_passed', as: 'alert_passed'
  get 'alert-unpassed', to: 'alerts#set_unpassed', as: 'alert_unpassed'
  get 'alert-blocked', to: 'alerts#set_blocked', as: 'alert_blocked'

  resources :tasks do
    resources :answers do
      # resources :comments
    end
  end

  resources :answers do
    resources :comments
      member do
        get 'toggle_like', to: 'answers#toggle_like', as: 'toggle_like'
      end
  end

  resources :tasks do
      member do
        get 'toggle_marked', to: 'tasks#toggle_marked', as: 'toggle_marked'
      end
  end

  # api
  namespace :api do
    namespace :v1 do
      resources :tasks, defaults: { format: :json } do
        resources :answers, defaults: { format: :json }
      end
      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"

        #post "update/:id", to: "users#update"
      end
    end

    namespace :v2 do
      resources :tasks, defaults: { format: :json } do
        resources :answers, defaults: { format: :json }  do
          resources :comments, defaults: { format: :jsom }
        end
      end
    end
  end

  resources :profiles, only: [:show, :edit, :update]

  namespace :admin do
    resources :tasks do
      resources :answers do
        resources :comments, except: :show
      end
    end

     resources :answers
    #   resources :comments, except: :show
    # end
    #
    resources :subscriptions
    root "admin/tasks#index"
  end

  get 'welcome', to: 'welcome#index'
  get 'about', to: 'welcome#about'
  get 'allTasks', to: 'welcome#allTasks'
  get 'searchTasks', to: 'welcome#searchTasks'
  get 'expireTasks', to: 'welcome#expireTasks'
  get 'howToPlay', to: 'welcome#howToPlay'
  get 'support', to: 'support#index'
  get 'answersGallery', to: 'tasks#answersGallery'

  root "welcome#index"

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :task
  belongs_to :user

  has_many :comments, :dependent => :destroy
  has_many :poly_comments, as: :commentable, dependent: :destroy

  has_many :likes
  has_many :users_who_liked, through: :likes, source: 'user'

  mount_uploader :answer_image, TaskImageUploader

  self.per_page = 4

  # validates :name, presence: true
  # validates :description, presence: true
  validates :answer_image, presence: true
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy ]

  # GET /answers or /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1 or /answers/1.json
  def show
    @comment = Comment.new
  end

  # GET /answers/new
  def new
    @task = Task.find(params[:task_id])
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
    # @task = @answer.task
  end

  # POST /answers or /answers.json
  def create
    @task = Task.find(params[:task_id])
    @answer = @task.answers.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to admin_task_url(@answer.task), notice: "answer was successfully created." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to admin_task_url(@answer.task), notice: "answer was successfully updated." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @task = @answer.task
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to admin_task_url(@task), notice: "answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_task
     @task = Task.find(params[:task_id])
   end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:answer_image).merge(user_id: current_user.id)
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show edit update destroy toggle_like]

  # GET /answers or /answers.json
  def index
    #@answers = Answer.all
    @task = Task.find(params[:task_id])
    @answers = Answer.where(task_id: @task.id).paginate(page: params[:page])
    # @comment = Comment.new
    # url = answer_comments_path(@answer, @comment)

    # Meta
    set_meta_tags(
      title: "Ответы",
      description: "Здесь собраны все ответы пользователей refs",
      keywords: "refs, reference, creative, answers"
    )
    # end
  end

  # GET /answers/1 or /answers/1.json
  def show
    @task = Task.find(params[:task_id])
    @answer = Answer.find(params[:id])
    @comment = Comment.new
    @url = answer_comments_path(@answer, @comment)
    # Meta
    set_meta_tags(
      title: "Ответ",
      description: "Зацени этот ответ на задание в refs",
      keywords: "refs, reference, creative, answer"
    )
    # end
  end

  # GET /answers/new
  def new
    @task = Task.find(params[:task_id])
    @answer = Answer.new
    #@answer = @task.answers.build
  end

  # GET /answers/1/edit
  def edit
     @task = @answer.task
  end

  # POST /answers or /answers.json
  def create
   @task = Task.find(params[:task_id])
    @answer = @task.answers.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to task_url(@task), notice: "answer was successfully created." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    @task = Task.find(params[:task_id])
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to task_url(@answer.task), notice: "answer was successfully updated." }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @task = @answer.task
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to task_url(@task), notice: "answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

    def toggle_like
    answer_user_ids = []

    @answer.users_who_liked.each do |user|
      answer_user_ids << user.id
    end

    if answer_user_ids.include?(current_user.id)
      current_user.answers_i_liked.delete(@answer)
    else
      current_user.answers_i_liked << @answer
    end

    @answer = Answer.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_task
     @task = Task.find(params[:task_id])
   end

    # Only allow a list of trusted parameters through.
     def answer_params
      params.require(:answer).permit(:answer_image).merge(user_id: current_user.id)
    end
end

app/controllers/api/v1/answers_controller.rb
class  Api::V2::AnswersController <  Api::V2::ApplicationController

  def index
    @answers = Answer.all
  end

  def show
    @task = Task.find(params[:task_id])
    # @comment = Comment.new
  end

  def create

    puts "======================="
    puts "REQUEST FROM FRONTEND"
    puts "======================="

    @user = User.find_by_jti(decrypt_payload[0]['jti'])

    @task = Task.find(params[:task_id])
      @answer = @task.answers.new(answer_image: params[:answer_image], user_id: current_user.id, description:params[:description])

    if @answer.save
      render json: @answer.as_json
    else
      render json: @answer.errors, status: :unprocessable_entity
    end
  end

  def answer_params
    params.require(:answer).permit(:answer_image).merge(user_id: current_user.id)
  end
end

app/controllers/api/v2/answers_controller.rb
class  Api::V2::AnswersController <  Api::V2::ApplicationController

  def index
    @answers = Answer.all
  end

  def show
    @task = Task.find(params[:task_id])
    @comment = Comment.new
  end

  def create

    puts "======================="
    puts "REQUEST FROM FRONTEND"
    puts "======================="

    @USER = User.find_by_jti(params[:jti])

    @task = Task.find(params[:task_id])
      @answer = @task.answers.new(answer_image: params[:answer_image], user_id: current_user.id, description:params[:description])

    respond_to do |format|
      if @answer.save
        format.json { render json: @answer.as_json }
      else
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div id="<%= dom_id answer %>">
  <div class="answerCard">
    <%= image_tag answer.answer_image.url,  class: "answerImg" if answer.answer_image.url %>

    <div class="answerBody">
      <p>  <%= answer.user.email %> </p>
    </div>

    <% if can? :manage, answer %>
      <div class="editButtons">
        <%= link_to "Редактировать", edit_task_answer_path(answer.task, answer), class:"button" %>
        <%= button_to "Удалить", task_answer_path(answer.task, answer), method: :delete, class:"button" %>
      </div>
    <% end %>
    <%= @task%>
    <%= @answer%>
    <div class="commentsContainer">
      <%#= render 'comments/form', task: @task, answer: answer, comment: Comment.new %>
      <%= render answer.comments, answer: answer, task: @task %>
    </div>
  </div>
</div>

app/views/answers/_answers_next_page_button.html.erb
<% if answers.next_page %>
  <%= link_to 'Загрузить ещё', answers_path(page: answers.next_page, task_id: @task.id), data: {turbo_stream: true, answers_target: 'nextButton' }, class: "opacity" %>
<% end %>

app/views/answers/_answers_page.html.erb
  <% @answers.each do | answer | %>
  <%  @comment = Comment.new
      @url = answer_comments_path(answer, @comment)%>
    <%= render 'answers_cards/answer_reels', task: @task, answer: answer, url: @url%>
  <% end %>

app/views/answers/_edit_form.html.erb
<%= form_with(url: task_answer_path(task)) do |form| %>

<h1>EDITTTT</h1>
  <div class="W_AnswerForm">

  <% if answer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="M_Uploader">
   <label for="A_UploadButton">
     <span class="A_UploadButtonText">Перетащите сюда фотку</span>
   </label>
   <%= form.file_field :answer_image, id:"A_UploadButton" %>
 </div>

<div class="W_Description">

  <div class="W_UserInfo">
    <div class="A_Ava xs">
      <%= image_tag current_user.avatar_image.extrasmall.url, class: "Q_Ava" if current_user.avatar_image.extrasmall.url %>
    </div>
    <p>@<%= current_user.email.tr('_@email.com', '')%></p>
  </div>

  <%= form.text_area :description, placeholder: "Добавьте описание", class: "A_Description" %>

</div>

	<div class="W_AnswerSaveButton">
		<%= form.submit "Опубликовать", :class => "M_Button primary"%>
	</div>

</div>
<% end %>

app/views/answers/_form.html.erb
  <%= form_with(model: @answer, url: task_answers_path(@task)) do |form| %>

  <div class="W_AnswerForm">

  <% if answer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="M_Uploader">
   <label for="A_UploadButton">
     <span class="A_UploadButtonText">Перетащите сюда фотку</span>
   </label>
   <%= form.file_field :answer_image, id:"A_UploadButton" %>
 </div>

<div class="W_Description">

  <div class="W_UserInfo">
    <div class="A_Ava xs">
      <%= image_tag current_user.avatar_image.extrasmall.url, class: "Q_Ava" if current_user.avatar_image.extrasmall.url %>
    </div>
    <p>@<%= current_user.email.tr('_@email.com', '')%></p>
  </div>

  <%= form.text_area :description, placeholder: "Добавьте описание", class: "A_Description" %>

</div>

	<div class="W_AnswerSaveButton">
		<%= form.submit "опубликовать", :class => "M_Button primary"%>
	</div>

</div>
<% end %>

app/views/answers/_like_button.html.erb
<%
  answer_user_ids = []

  answer.users_who_liked.each do |user|
    answer_user_ids << user.id
  end

  counter = answer_user_ids.count 

  if current_user
    icon_class = answer_user_ids.include?(current_user.id) ? "active" : "inactive"
  else
    icon_class = "inactive"
  end
%>

<%= turbo_frame_tag dom_id(answer) do %>
    <a class="A_ButtonsTape" href="<%= toggle_like_answer_path(answer) %>">
      <div class="Q_Icon like <%=icon_class%>"></div>
      <p class="Q_Count"><%=counter%></p>
    </a>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render "edit_form", task: @task, answer: @answer %>

app/views/answers/index.html.erb
<body id="reels">
<div class="Q_Grid">

<div class="A_TopRow"> 
  <%= link_to '', :back, class: "A_ArrowBack" %>
  <div class="W_Filters">
    <p class="active">новые</p> 
    <p class="inactive">популярные</p> 
  </div>
</div>

<div class="M_TaskHintInReel">
  <%= render 'task_cards/task_card', task: @task%>
  <div class="A_TimeLeft"><%= distance_of_time_in_words_to_now(@task.created_at + 3.days) %></div>
  <% if can? :create, Answer %>
    <%= link_to "загрузить находку", new_task_answer_path(@task.id), class: "M_Button m primary", task: @task %>
  <% end %>
</div>

<div id="answers" class="S_AnswersReels" data-controller="answers">
  <%= turbo_frame_tag 'answers' do %>  
    <%= render partial: 'answers_page', locals: { answers: @answers, task: @task } %>
  <% end %>
  <%#= render partial: 'answers_page', answers: @answers %>
  <%= turbo_frame_tag 'answers_pagination' do %>
    <%= render partial: 'answers_next_page_button', locals: { answers: @answers, task: @task } %>
  <% end %>
</div>
</div>
</body>

app/views/answers/index.turbo_stream.erb
<%= turbo_stream.append 'answers', partial: 'answers_page', locals: { answers: @answers, task: @task } %>
<%= turbo_stream.update 'answers_pagination', partial: 'answers_next_page_button', locals: { answers: @answers, task: @task } %>

app/views/answers/new.html.erb
<div class="Q_Grid">
<div class="O_AnswerForm">
  <div class="Q_Rect first"></div>
  <div class="Q_Rect second"></div>
  <div class="Q_Rect third"></div>
  <div class="W_AnswerFormContainer">
    <%= render 'task_cards/card_with_two_buttons', task: @task%>
    <%= render "form", task: @task, answer: @answer %>
  </div>
</div>
</div>

app/views/answers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @answer %>

<h3>Comments</h3>
<br>
<br>
<%= render "comments/form", task: @task, answer: @answer, comment: Comment.new, url: url %>
<%= render @answer.comments, answer: @answers %>

 <%#= link_to "New comment", new_task_answer_comment_path(@task, @answer) %>

<br>
<br>

  <% if can? :manage, @answer %>
      <div class="editButtons">
        <%= link_to "Редактировать", edit_task_answer_path(@answer.task, @answer), class:"button" %>
        <%= link_to "Back to answers", task_answers_path %>
        <%= button_to "Удалить", task_answer_path(@answer.task, @answer), method: :delete, class:"button" %>
      </div>
  <% end %>

app/views/answers/toggle_like.html.erb
 <%= render 'answers/like_button', answer: @answer, task: @task %>